name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Fix Gradle for Version 9+
      run: |
        # Update settings.gradle for Gradle 9 compatibility
        cat > settings.gradle << 'SETTINGS'
        pluginManagement {
            repositories {
                google()
                mavenCentral()
                gradlePluginPortal()
            }
        }
        dependencyResolutionManagement {
            repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
            repositories {
                google()
                mavenCentral()
            }
        }
        rootProject.name = "RansomwareEducationApp"
        include ':app'
        SETTINGS
    - name: Build APK
      run: |
        gradle assembleDebug --no-daemon --stacktrace
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk-artifact
        path: "**/*.apk"
        if-no-files-found: ignore
